version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kick-viewer-simulator
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./vpn:/etc/openvpn/client
      - ./data:/data
      - ./screenshots:/app/screenshots
      - ./logs:/app/logs
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/kick-viewer-simulator
      - VPN_CONFIGS_PATH=/etc/openvpn/client
      - LOG_LEVEL=info
    cap_add:
      - NET_ADMIN  # Required for OpenVPN networking
    devices:
      - /dev/net/tun:/dev/net/tun  # Required for OpenVPN
    depends_on:
      - mongodb
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongodb:
    image: mongo:6
    container_name: kick-mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27018:27017"
    networks:
      - app-network
    command: ["--bind_ip_all"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-password}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
